export const GET_BLOG_DATA_REQUEST = "GET_BLOG_DATA_REQUEST"
export const GET_BLOG_DATA_SUCCESS = "GET_BLOG_DATA_SUCCESS"
export const GET_BLOG_DATA_FAILURE = "GET_BLOG_DATA_FAILURE"

export const POST_BLOG_DATA_REQUEST = "POST_BLOG_DATA_REQUEST"
export const POST_BLOG_DATA_SUCCESS = "POST_BLOG_DATA_SUCCESS"
export const POST_BLOG_DATA_FAILURE = "POST_BLOG_DATA_FAILURE"

export const DELETE_BLOG_DATA_REQUEST = "DELETE_BLOG_DATA_REQUEST"
export const DELETE_BLOG_DATA_SUCCESS = "DELETE_BLOG_DATA_SUCCESS"
export const DELETE_BLOG_DATA_FAILURE = "DELETE_BLOG_DATA_FAILURE"

export const UPDATE_BLOG_DATA_REQUEST = "UPDATE_BLOG_DATA_REQUEST"
export const UPDATE_BLOG_DATA_SUCCESS = "UPDATE_BLOG_DATA_SUCCESS"
export const UPDATE_BLOG_DATA_FAILURE = "UPDATE_BLOG_DATA_FAILURE"